config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,              only: [:new, :destroy, :create]
  resources :relationships, :microposts,         only: [:create, :destroy      ]
  resources :password_resets
  resources :account_confirmations, only: [:new, :create          ]
  root 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/controllers/account_confirmations_controller.rb
class AccountConfirmationsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_account_confirmation_token(params[:account_confirmation])
  	if user.nil?
  	  flash.now[:error] = "Token invalid"
  	  render 'new'
  	elsif user.update_attribute(:confirmed, true)
  	  redirect_to root_path, :notice => "account confirmed"
  	else
  	  redirect_to users_path
  	end

  end

end

app/helpers/account_confirmations_helper.rb
module AccountConfirmationsHelper
end

app/views/account_confirmations/new.html.erb
<% provide(:title, "Confirm Account") %>
<h1> Confirm Account </h1>

<div class = "row" >
	<div class="span6 offset3">
		<%= form_tag account_confirmations_path do %>

		  <%= label_tag "Confirm Account" %>
		  <%= text_field_tag :account_confirmation %>

		  <%= submit_tag "Confirm", class: "btn btn-large btn-primary" %>
		
		<% end %>
	</div>
</div>